### ISSUE TITLE
Попраить вид таблицы Активити

### ISSUE THREAD

**Issue by detergen** [detergen/xduck#16]
- Нужно убрать колонки Id, Owner. Добавить Note, Tag, сумму первого
  Order (оч трудно работать), нынешний тотал оставить. 
- Если можно задать сортировку по умолчанию, то нужна сортировка по
  дате (последняя дата - первая в списке).
- В уменьшить высоту строки в таблицах на 25%
- Фильтр должен быть сразу открыт в шапке таблицы

**Comment by detergen** [comment]
Уменьшить высоту строки на 25%, значит не шрифт, а высоту строки, шрифт тот-же, что был норм. Не помню как эти отступы называются вертикальные между рамкой и шрифтом padding, наверное в 0.

. table.table.wice-grid tr td, table.table.wice-grid tr th {
    padding: 0px;

**Comment by denstep** [comment]
они уменьшены уже, если совсем свести на нет - будет совсем некрасиво. 
Сейчас попробую сделать с 4 на 2, также уменьшил кнопки включая их шрифт

**Comment by denstep** [comment]
Насколько я вижу проблема на небольшом экране остается в кнопках.. чтобы ее решить надо либо их еще уменьшать либо убирать колонки

**Comment by denstep** [comment]
скриншоты отправлю в телеграмм

**Comment by detergen** [comment]
Пока закроем вопрос, ибо  на мой взгляд идеальная высота теперь.
