### ISSUE TITLE
Добавить единицы измерения

### ISSUE THREAD

**Issue by detergen** [detergen/xduck#4]
Добавить UOMS
в продуктах д. быть выбор в чем мерить продукты
в отчетах подтягиваться из словаря ед. изм.

ед.измер такие:
м, шт, компл, мешки, коробка, палета, куб.м. кв.м кг т

**Comment by denstep** [comment]
какие имеются ввиду отчеты ?

**Comment by detergen** [comment]
Сейчас нет в системе единиц измерения. В kontador  была неправильна названа (SKU) должна быть  UOM. В отчетах в odt файлы приходится руками вписывать.

**Comment by denstep** [comment]
всеравно не очень понятно. 
Единицы измерения я добавил (пока в своем барнчике), как это отражается в отчетах ?
Может вы подправите шаблоны отчетов, и добавите туда переменные в которые я подставлю единицы измерения ? Либо обсудим это по телефону ?

**Comment by detergen** [comment]
На продакшн сервере лежат шаблоны в них я поставил "шт", вместо "шт" д.быть [UOM]

**Comment by detergen** [comment]
Поправка к предыдущему посту...  в шаблоне сейчас поле UOM называется SKU, но вместо SKU скрипт подставяет prduct.name. В скрипте поправил на шт, но сейчас опять все по старому... т.к.деплой не налажен полностью.

**Comment by denstep** [comment]
в пул реквесте висит и этот апдейт

**Comment by denstep** [comment]
удалось ли посмотреть ? все ли впорядке ?
