### ISSUE TITLE
Фильтр по организации в гриде активити не работает

### ISSUE THREAD

**Issue by detergen** [detergen/xduck#7]
Открываем грид активити пытаемся фильтровать по организации - ошибка
UPD: From Organization  To Organization при попытке сортировать тоже падает

**Comment by denstep** [comment]
https://github.com/detergen/xduck/pull/8

**Comment by denstep** [comment]
у меня не удается воспроизвести эту проблему после обновления кода с этим коммитом, вы можете дать ссылку на ту активити в которой не работает фильтр ?

**Comment by detergen** [comment]
Ну я и закрыл этот issue почти неделю назад
